#!/usr/bin/env bash
#Iterating through "Best School" 10 times using the while loop and the if loop to check a condition
i=0
while [[ $i -ne 10 ]]
do
  if [ $i == 9 ]
  then
    echo "Best School \nHi"
    ((i++))
  else
    echo "Best School"
    ((i++))
  fi
done
  
