#!/usr/bin/env bash
# Managing the "manage_my_process" file
if [[ $1 = "start" ]]
then
	./manage_my_process &
	echo $! > my_process.pid
	sudo mv my_process.pid /var/run/
	echo "manage_my_process started"
elif [[ $1 = "stop"  ]]
then
	kill "$( cat /var/run/my_process.pid )"
	sudo rm /var/run/my_process.pid
	echo "manage_my_process stopped"
elif [[ $1 = "restart"  ]]
then
	kill "$( cat /var/run/my_process.pid )"
	sudo rm /var/run/my_process.pid
	./manage_my_pocess &
	echo $! > my_process.rpid
	sudo mv my_process.pid /var/run/
	echo "manage_my_process restarted"
else
	echo "Usage: manage_my_procss {start|stop|restart}"
fi
