#!/usr/bin/env bash
#Displaying a text indefinitely with a sleep 2 between each iteration and displaying "I am invicible" when receiving a SIGTERM signal
trap 'echo "I am invincible!!!"' SIGTERM
while true
do
    echo "To infinity and beyond"
    sleep 2
done
